- name: Add user {{ jenkins_user }}
  user: name="{{ jenkins_user }}" shell=/bin/bash

- name: Creates directories
  file: path="{{ item }}" owner="{{ jenkins_user }}" group="{{ jenkins_user }}" state=directory
  with_items: "{{ jenkins_dirs }}"

- name: Install Java
  apt: name=openjdk-8-jre

- name: Install Java
  apt: name=openjdk-8-jdk
